name: Tests
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  Ubuntu-Tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true

      - name: Install libpcap
        run: sudo apt-get install -y libpcap-dev

      - name: Initialize build system
        run: cmake -G "Unix Makefiles" -S . -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build tests
        run: cmake --build build --target tests

      - name: Run tests
        run: ctest -V --test-dir build/
